### ISSUE TITLE
How points are awarded to the red team and the blue team

### ISSUE THREAD

**Issue by ghost** [mitre/gameboard#22]
Hello, please tell me how and for what points are awarded in the gameboard plugin in red and blue. Sometimes an ability is awarded several points in both blue and red. And what determines the final score in the game?

**Comment by garunagiri** [comment]
Happy to see that you're using the gameboard plugin!

The scoring rules for links are as follows:
- A red ability that has no corresponding blue abilities will receive a certain score based on the tactic it performed. For example, discovery nets 1 point while persistence gets 6 points.
- A red ability that has at least one corresponding blue ability will get 0 points.
- Every blue ability that corresponds to a red ability will receive a certain number of points depending on the tactic it performs, just like red abilities. For example, a detection ability receives 2 points while a response ability receives 3.
- A blue ability that does not correspond to a red ability receives -1 points, as the ability is considered out-of-scope.

The final score for each team is the sum of the individual link scores, with one modification:
   - The blue team will have one or two points deducted for each red ability that did not receive a response from the blue team, depending on how visible the red ability is determined to be. In most cases, this should be a 2 point deduction.

Can you clarify what you mean by an ability being awarded several points in both blue and red please?

**Comment by ghost** [comment]
Very interesting. Where can I read about scoring for each tactic? Or can you please write me down.
I understand correctly points are awarded for each ability from the type of tactics. For example: for each ability from the discovery tactic I get one point or for each ability from the persistence tactic I get 6 points. Do I understand you correctly?

Can you clarify what you mean by an ability being awarded several points in both blue and red please? You answered my question :) I thought all abilities are assigned one point.

**Comment by ghost** [comment]
sorry i accidentally closed my question just wanted to edit it

**Comment by garunagiri** [comment]
We don't have specific documentation on the scoring values for each tactic, but the weighting can be found here:
https://github.com/mitre/gameboard/blob/83ff43664fc43660b6d0c1ac08448228d193b8bf/app/gameboard_api.py#L21

Any tactics that don't fall into one of these is assigned 1 point, as seen here:
https://github.com/mitre/gameboard/blob/83ff43664fc43660b6d0c1ac08448228d193b8bf/app/gameboard_api.py#L179

Your understanding is correct. If an ability is to be awarded points, for example a red ability that has no corresponding blue abilities, then depending on its tactic it will get anywhere from 1 to 6 points. 

I hope this answers your questions!

**Comment by ghost** [comment]
Thank you very much for your answer. It would be nice if you entered this data into the documentation, then you would not have to look for them.
I have a couple more questions.
RED_POINT_MAPPING does not contain all the tactics that are in the caldera, such as command and control which gets three points, are there a few more tactics missing?
And the second question, I am not capturing the red team by the blue ones, I explain: when I start a manual operation not auto-collect (blue agent), the points of the blue team are always in the red, but if through the response plugin I select and save one of the four defender auto-collect then capture of the reds will proceed. In short, the blue manual operation does not work, only auto-collection works.
And one more question is ripe while I was writing this message. Why when I go to defenders (blue agent) and create a new profile and save it, it is not displayed in the response plugin, there are still 4 defenders, a new one is not added for auto-collection

**Comment by garunagiri** [comment]
> RED_POINT_MAPPING does not contain all the tactics that are in the caldera, such as command and control which gets three points, are there a few more tactics missing?

Not all tactics are within the mapping, yes. Any that aren't there are assigned 1 point as default:
https://github.com/mitre/gameboard/blob/83ff43664fc43660b6d0c1ac08448228d193b8bf/app/gameboard_api.py#L179

> It would be nice if you entered this data into the documentation, then you would not have to look for them.

The reason that this information isn't in the documentation is that value assignments for tactics are somewhat arbitrary. We wanted to provide the capability for tactic-specific point assignments, but changing these assignments based on each each user's needs is also encouraged. The current values aren't necessarily one-size-fits-all.

> And the second question, I am not capturing the red team by the blue ones, I explain: when I start a manual operation not auto-collect (blue agent), the points of the blue team are always in the red, but if through the response plugin I select and save one of the four defender auto-collect then capture of the reds will proceed. In short, the blue manual operation does not work, only auto-collection works.

Only the Auto-Collect operation's links are automatically associated with a corresponding red link. Any other blue operations need to have their links manually pinned to the corresponding red link. This is why you aren't seeing the points on the blue side for the blue manual operation.

> Why when I go to defenders (blue agent) and create a new profile and save it, it is not displayed in the response plugin, there are still 4 defenders, a new one is not added for auto-collection

Custom abilities and adversaries/defenders are currently stored within a directory outside of the response plugin. When Caldera is started with the `-fresh` argument, these are purged from the system. Because they are stored outside the response plugin, they aren't treated as part of the Response plugin, which is why the defender you created doesn't show up in that list. However, if you look back in the Defenders modal, you'll see your new defender there! You'll be able to use it for any operations as well.

**Comment by ghost** [comment]
@garunagiri Please tell me how the user abilities of the defenders to me link to the red link. How can i do this ?
