### ISSUE TITLE
blue team points

### ISSUE THREAD

**Issue by ghost** [mitre/gameboard#27]
Hello again @garunagiri, can you please explain one point with the scoring of the blue team. Did I understand correctly if, if the blue ability is successful, then it gets:
  detection: 2
  hunt: 3
  response: 3
The rest of the tactics get 1 point. And if the ability does not work, it gets -1 point. And in what cases does the ability get -2 points?

**Comment by garunagiri** [comment]
Hi @veslo94,

That's correct, those are the blue points per tactic.

The difference between -1 points and -2 points has to do with red ability visibility. Visibility is used to describe how much noise an ability is expected to make on the target system. By default, abilities are given a visibility score of 50. This score can be changed at runtime based on various facts discovered by the operation. The rules for changing visibility are set within the `adjustments` field in the source used for the operation.

I may have mentioned previously that a red ability that isn't responded to results in -1 point for the blue team. I realize now that that's incorrect in the default case. A red ability with a visibility of 50 or greater results in -2 points for the blue team, which is what will happen by default.

I hope this clears things up : )

**Comment by ghost** [comment]
@garunagiri You said, that abilities are given a visibility score of 50. 
I haven’t seen such information before, what is the visibility assessment and what is it for?

**Comment by garunagiri** [comment]
I did, yes. Visibility is a field within Caldera that isn't widely used, but exists for use in situations where defenses found on the network should impact the decision making process in terms of deciding what abilities to run. For example, it's likely unwise to attempt to drop Mimikatz to disk on a target that's found to have Anti-Virus running.

A brief description of Visibility can be found here: https://caldera.readthedocs.io/en/latest/Learning-the-terminology.html?highlight=visibility#what-is-an-operation

As the description states, all abilities are given a visibility score of 50 by default. Because the operation is given a default visibility threshold of 51, visibility usually does not play a role. However, it's possible to include 'adjustments' that modify the visibility scores of abilities based on facts that are found over the course of the operation.

An example of adjustments can be found in the basic fact source: `ed32b9c3-9593-4c33-b0db-e2007315096b.yml`.

`adjustments:
    1b4fb81c-8090-426c-93ab-0a633e7a16a7:
      host.installed.av:
        - value: symantec
          offset: 3
        - value: mcafee
          offset: 3`

In this example, the ability referenced by `1b4fb81c-8090-426c-93ab-0a633e7a16a7`, which sniffs the network from a target host, will have its visibility score increased by 3 points if a fact `host.installed.av` with value 'symantec' or 'mcafee' is found in the operation. Given the default ability visibility score of 50 and default operation visibility threshold of 51, this ability will have a visibility score of 53 and therefore not be run.

I hope this helps you understand what purpose visibility serves.

If you are not using visibility adjustments in your operations, each red ability that is not responded to causes a -2 score modification for the blue team.

**Comment by wbooth** [comment]
Thank you, if there is anything else we can help with please feel free to re-open this ticket or open a new one.

**Comment by ghost** [comment]
@wbooth good, thanks I will keep in mind =)
